name: terraform-deploymment-workflows
run-name: terraform continuous integration
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

# @TODO change to env variable

jobs:
  assume-aws-role:
    runs-on: ubuntu-latest

    # take the env first
    environment: dev

    # permissions with env
    permissions:
        id-token: write
        contents: read
    steps:
      - name: git clone the repository
        uses: actions/checkout@v4
      # additional for easy tracking
      - name: set timestamp
        id: timestamp_generator
        run: |
            SUFFIX=$(date +'%d%m%H')
            echo "session_id=github_action_terraform_$SUFFIX" >> $GITHUB_OUTPUT
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ vars.AWS_REGION }}
          role-session-name: ${{ steps.timestamp_generator.outputs.session_id }}
      # verification
      - name: sts GetCallerIdentity
        run: |
          aws sts get-caller-identity