name: terraform-deploymment-workflows
run-name: terraform continuous integration
on: [push]

jobs:
    check-running-environment:
        if: ${{ github.ref == 'refs/heads/main' }}
        runs-on: ubuntu-latest
        steps:
            - run: echo "Deploying to production environment, from branch $GITHUB_REF"