name: terraform-deploymment-workflows
run-name: terraform continuous integration
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

# @TODO change to env variable

jobs:
  evaluate-target-environment:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
        - name: output environment variable
          id: verbose_log
          run: |
            ENV_TO_RUN="dev"
            echo "Currently take code from $GITHUB_REF, with env $ENV_TO_RUN"
            echo "target_env=$ENV_TO_RUN" >> $GITHUB_OUTPUT
    outputs:
        env_value: ${{ steps.verbose_log.outputs.target_env }}

  job-set-up-and-run:
    runs-on: ubuntu-latest
    needs: evaluate-target-environment

    # take the env first
    environment: ${{ needs.evaluate-target-environment.outputs.env_value }}

    # permissions with env
    permissions:
        id-token: write
        contents: read
    steps:
      - name: git clone the repository
        uses: actions/checkout@v4  
      - name: terraform setup
        uses: hashicorp/setup-terraform@v3
      # additional for easy tracking
      - name: set timestamp
        id: timestamp_generator
        run: |
            SUFFIX=$(date +'%d%m%H')
            echo "session_id=github_action_terraform_$SUFFIX" >> $GITHUB_OUTPUT
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ vars.AWS_REGION }}
          role-session-name: ${{ steps.timestamp_generator.outputs.session_id }}
      # verification
      - name: sts GetCallerIdentity
        run: |
          aws sts get-caller-identity
      # terraform
      - name: terraform init and validate
        working-directory: ./env/${{ needs.evaluate-target-environment.outputs.env_value }}
        run: |
            terraform init
            terraform validate
            